### ISSUE TITLE
Tornado Client hits StreamClosedException

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-data-processing#2]
Flask is by default blocking HTTP server.  The client calling the DP API is using tornado to quickly get all responses for multiple images.  When sending multiple requests with tornado, the following error gets hit:

```
[ERROR]:[tornado.application]: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/http1connection.py", line 222, in _read_message
    yield body_future
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/tornado/http1connection.py", line 589, in _read_fixed_body
    min(self.params.chunk_size, content_length), partial=True)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/http1connection.py", line 261, in _read_message
    delegate.on_connection_close()
  File "/usr/local/lib/python3.6/site-packages/tornado/http1connection.py", line 683, in on_connection_close
    return self._delegate.on_connection_close()
  File "/usr/local/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 472, in on_connection_close
    raise self.stream.error
  File "/usr/local/lib/python3.6/site-packages/tornado/iostream.py", line 945, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/usr/local/lib/python3.6/site-packages/tornado/iostream.py", line 1238, in read_from_fd
    return self.socket.recv_into(buf)
ConnectionResetError: [Errno 104] Connection reset by peer
```

This is an `async` vs `sync` issue I believe.  StackOverflow leads me to think that using another HTTP Server besides the default WSGI would be helpful (and probably a best practice for production deployment)

**Comment by willgraf** [comment]
Fixed by #7, which replaces the HTTP API with a gRPC API.  No longer using Tornado, so this issue can be closed.
